### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kozak243**
minor tweaks to make it work again

### CODE REVIEW

**Comment by rredford** [comment]
Why is 2 files added? It don't seem to be used by 2 scripts.

**Comment by kozak243** [comment]
"from os import path
from xml.sax.saxutils import escape"
without them python doesn't know what path and escape is

**Comment by kozak243** [comment]
sorry, i'm just dumb as heck 😕

**Comment by rredford** [comment]
No problem, make new one, not including those two and I will accept the change :)

**Pull request closed without merging**
